
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Isidoro
 */
public class FormularioA extends javax.swing.JPanel {
    
    //Atributos usados
    Persona cliente;
    CuentaAhorro cuenta;
    /**
     * Creates new form FormularioA
     */
    public FormularioA() {
        setBounds(10, 10, 10, 10);
        setVisible(true);
        initComponents();
    }
    
    public void mostrarDatos(CuentaBancaria cuenta_ini) {
        CuentaAhorro cuenta_mostrar = (CuentaAhorro) cuenta_ini;
        txt_Nombre.setText(cuenta_mostrar.titular.nombre);
        txt_Apellidos.setText(cuenta_mostrar.titular.apellidos);
        txt_F_nac.setText(cuenta_mostrar.titular.fecha_nacimiento);
        txt_ccc.setText(cuenta_mostrar.ccc);
        txt_Saldo.setText(Double.toString (cuenta_mostrar.saldo));
        txt_interes.setText(Float.toString(cuenta_mostrar.tipo_interes));
        btn_ClienteAhorro.setEnabled(false);
    }
    
    public void activarBoton() {
        btn_ClienteAhorro.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Nombre_Persona = new java.awt.Label();
        txt_Nombre = new java.awt.TextField();
        lbl_Apellidos = new java.awt.Label();
        txt_Apellidos = new java.awt.TextField();
        lbl_f_nac = new java.awt.Label();
        txt_F_nac = new java.awt.TextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_ccc = new java.awt.Label();
        txt_ccc = new java.awt.TextField();
        lbl_saldo = new java.awt.Label();
        txt_Saldo = new java.awt.TextField();
        lbl_interes = new java.awt.Label();
        txt_interes = new java.awt.TextField();
        btn_ClienteAhorro = new java.awt.Button();

        lbl_Nombre_Persona.setText("Nombre:");

        lbl_Apellidos.setText("Apellidos:");

        lbl_f_nac.setText("Fecha de nacimiento:");

        txt_F_nac.setText("dd/mm/yyyy");

        lbl_ccc.setText("Número de Cuenta:");

        txt_ccc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_ccc.setMaximumSize(new java.awt.Dimension(20, 20));
        txt_ccc.setMinimumSize(new java.awt.Dimension(20, 20));
        txt_ccc.setName(""); // NOI18N

        lbl_saldo.setText("Saldo inicial:");

        lbl_interes.setText("Tipo de interés:");

        btn_ClienteAhorro.setLabel("Generar Cuenta");
        btn_ClienteAhorro.setName(""); // NOI18N
        btn_ClienteAhorro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ClienteAhorroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_f_nac, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_F_nac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Nombre_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addComponent(lbl_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lbl_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_Saldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_ccc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_ccc, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_interes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_interes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ClienteAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Nombre_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_f_nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_F_nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_ccc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ccc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_interes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_interes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(btn_ClienteAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ClienteAhorroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ClienteAhorroMouseClicked
        // TODO add your handling code here:
        String nombre = txt_Nombre.getText();
        String apellidos = txt_Apellidos.getText();
        String fecha = txt_F_nac.getText();
        cliente = new Persona(nombre, apellidos, fecha);
        try {
            String ccc = txt_ccc.getText();
            boolean validar = AplicacionCuentaBancaria.ValidaCCC(ccc);
            if (validar) {
                JOptionPane.showMessageDialog(null, "Cuenta correcta", "Validación de Cuenta", JOptionPane.INFORMATION_MESSAGE);
                ccc = ccc.trim();
                ccc = ccc.replace(" ", "");
                
                double saldo = Double.parseDouble(txt_Saldo.getText());
                float interes = Float.parseFloat(txt_interes.getText());
                cuenta = new CuentaAhorro(cliente, saldo, ccc, interes);
                AplicacionCuentaBancaria.Cuentas.add(cuenta);
                JOptionPane.showMessageDialog(null,"Cuenta de Ahorro creada", "Cuenta de Ahorro",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "La cuenta no ha superado la validación", "Validación de Cuenta", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error al crear la cuenta, por favor compruebe que los datos son correctos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_btn_ClienteAhorroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_ClienteAhorro;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label lbl_Apellidos;
    private java.awt.Label lbl_Nombre_Persona;
    private java.awt.Label lbl_ccc;
    private java.awt.Label lbl_f_nac;
    private java.awt.Label lbl_interes;
    private java.awt.Label lbl_saldo;
    private java.awt.TextField txt_Apellidos;
    private java.awt.TextField txt_F_nac;
    private java.awt.TextField txt_Nombre;
    private java.awt.TextField txt_Saldo;
    private java.awt.TextField txt_ccc;
    private java.awt.TextField txt_interes;
    // End of variables declaration//GEN-END:variables
}
