
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Isidoro
 */
public class FormularioB extends javax.swing.JPanel {
    
    Persona cliente;
    CuentaEmpresa cuenta;
    HashMap<String, Double> entidades;
    /**
     * Creates new form FormularioA
     */
    public FormularioB() {
        setBounds(10, 10, 10, 10);
        setVisible(true);
        initComponents();
    }
    
    public void activarBoton() {
        btn_ClienteAhorro.setEnabled(true);
    }
    
    public void mostrarDatos(CuentaBancaria cuenta_ini) {
        CuentaEmpresa cuenta_mostrar = (CuentaEmpresa) cuenta_ini;
        txt_Nombre.setText(cuenta_mostrar.titular.nombre);
        txt_Apellidos.setText(cuenta_mostrar.titular.apellidos);
        txt_F_nac.setText(cuenta_mostrar.titular.fecha_nacimiento);
        txt_ccc.setText(cuenta_mostrar.ccc);
        txt_Saldo.setText(Double.toString (cuenta_mostrar.saldo));
        txt_Tipo.setText(Float.toString(cuenta_mostrar.tipo_descubierto));
        txt_Maximo.setText(Float.toString(cuenta_mostrar.maximo));
        
        //Creo un iterador para recorrer el HashMap.
        Iterator it = cuenta_mostrar.lista.keySet().iterator(); //el iterador obtiene las key del hashMap
        int contador_linea = 0;
        while(it.hasNext()) {
            String entidad = it.next().toString();
            Tb_entidad.setValueAt(entidad, contador_linea, 0);
            Tb_entidad.setValueAt(cuenta_mostrar.lista.get(entidad), contador_linea, 1);
            contador_linea++;
        }
         
        btn_ClienteAhorro.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Nombre = new java.awt.TextField();
        lbl_Apellidos = new java.awt.Label();
        lbl_Nombre_Persona = new java.awt.Label();
        txt_Apellidos = new java.awt.TextField();
        lbl_f_nac = new java.awt.Label();
        txt_F_nac = new java.awt.TextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_ccc = new java.awt.Label();
        txt_ccc = new java.awt.TextField();
        lbl_saldo = new java.awt.Label();
        txt_Saldo = new java.awt.TextField();
        btn_ClienteAhorro = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Tipo = new javax.swing.JTextField();
        txt_Maximo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tb_entidad = new javax.swing.JTable();

        lbl_Apellidos.setText("Apellidos:");

        lbl_Nombre_Persona.setText("Nombre:");

        lbl_f_nac.setText("Fecha de nacimiento:");

        txt_F_nac.setText("dd/mm/yyyy");

        lbl_ccc.setText("Número de Cuenta:");

        txt_ccc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_ccc.setMaximumSize(new java.awt.Dimension(20, 20));
        txt_ccc.setMinimumSize(new java.awt.Dimension(20, 20));
        txt_ccc.setName(""); // NOI18N

        lbl_saldo.setText("Saldo inicial:");

        btn_ClienteAhorro.setLabel("Generar Cuenta");
        btn_ClienteAhorro.setName(""); // NOI18N
        btn_ClienteAhorro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ClienteAhorroMouseClicked(evt);
            }
        });

        jLabel1.setText("Entidadades autorizadas");

        jLabel2.setText("Tipo descubierto:");

        jLabel3.setText("Máximo descubierto:");

        Tb_entidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código entidad", "Recibo máximo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tb_entidad.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Tb_entidad);
        if (Tb_entidad.getColumnModel().getColumnCount() > 0) {
            Tb_entidad.getColumnModel().getColumn(0).setResizable(false);
            Tb_entidad.getColumnModel().getColumn(0).setHeaderValue("Código entidad");
            Tb_entidad.getColumnModel().getColumn(1).setResizable(false);
            Tb_entidad.getColumnModel().getColumn(1).setHeaderValue("Recibo máximo");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_f_nac, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_F_nac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Nombre_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addComponent(lbl_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Saldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Maximo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbl_ccc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_ccc, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_ClienteAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 160, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Nombre_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_f_nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_F_nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_ccc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ccc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Maximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                        .addComponent(btn_ClienteAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ClienteAhorroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ClienteAhorroMouseClicked
        // TODO add your handling code here:
        String nombre = txt_Nombre.getText();
        String apellidos = txt_Apellidos.getText();
        String fecha = txt_F_nac.getText();
        cliente = new Persona(nombre, apellidos, fecha);
        try {
            String ccc = txt_ccc.getText();
            boolean validar = AplicacionCuentaBancaria.ValidaCCC(ccc);
            if (validar) {
                JOptionPane.showMessageDialog(null, "Cuenta correcta", "Validación de Cuenta", JOptionPane.INFORMATION_MESSAGE);
                ccc = ccc.trim();
                ccc = ccc.replace(" ", "");
                double saldo = Double.parseDouble(txt_Saldo.getText());
                
                //DefaultTableModel modtabla = (DefaultTableModel) Tb_entidad.getModel(); //Obtenemos el modelo de la tabla, que es la que almacena los datos
                entidades = new HashMap<>();
                //IMPORTANTE: Funcionó después de cambiar en Design, en la JTable, el Type en String y Double
                
                try {
                    entidades.put(Tb_entidad.getValueAt(0,0).toString(), (double) Tb_entidad.getValueAt(0,1));    
                    entidades.put(Tb_entidad.getValueAt(1,0).toString(), (double) Tb_entidad.getValueAt(1,1));
                    entidades.put(Tb_entidad.getValueAt(2,0).toString(), (double) Tb_entidad.getValueAt(2,1));
                    entidades.put(Tb_entidad.getValueAt(3,0).toString(), (double) Tb_entidad.getValueAt(3,1));
                    entidades.put(Tb_entidad.getValueAt(4,0).toString(), (double) Tb_entidad.getValueAt(4,1));
                    entidades.put(Tb_entidad.getValueAt(5,0).toString(), (double) Tb_entidad.getValueAt(5,1));
                } catch (Exception j) {
                    //JOptionPane.showMessageDialog(null,"Error al leer la segunda línea", "Error", JOptionPane.ERROR_MESSAGE);
                }
                                              
                float tipo = Float.parseFloat(txt_Tipo.getText());
                float maximo = Float.parseFloat(txt_Maximo.getText());
                cuenta = new CuentaEmpresa(cliente, saldo, ccc, entidades, tipo, maximo);
                AplicacionCuentaBancaria.Cuentas.add(cuenta);
                JOptionPane.showMessageDialog(null,"Cuenta corriente creada", "Cuenta Corriente",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "La cuenta no ha superado la validación", "Validación de Cuenta", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error al crear la cuenta, por favor compruebe que los datos son correctos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ClienteAhorroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tb_entidad;
    private java.awt.Button btn_ClienteAhorro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label lbl_Apellidos;
    private java.awt.Label lbl_Nombre_Persona;
    private java.awt.Label lbl_ccc;
    private java.awt.Label lbl_f_nac;
    private java.awt.Label lbl_saldo;
    private java.awt.TextField txt_Apellidos;
    private java.awt.TextField txt_F_nac;
    private javax.swing.JTextField txt_Maximo;
    private java.awt.TextField txt_Nombre;
    private java.awt.TextField txt_Saldo;
    private javax.swing.JTextField txt_Tipo;
    private java.awt.TextField txt_ccc;
    // End of variables declaration//GEN-END:variables
}
